// pk200: '#FBA7FD',
// ye200: '#F9F79F',
// rd500: '#F55353',
// gr500: '#45E02A',

export const MainEventData = [
  {
    id: '1',
    tags: [
      { color: 'pk200', text: 'LIVE' },
      { color: 'ye200', text: '콘텐츠' },
    ],
    title: '한 대 빵!! (버블슈트 부딪치기)',
    startTime: '11:00',
    endTime: '17:00',
    location: '잔디공터',
    isSun: true,
  },
  {
    id: '2',
    tags: [
      { color: 'pk200', text: 'LIVE' },
      { color: 'ye200', text: '콘텐츠' },
    ],
    title: '삐에로 아저씨 풍선쇼',
    startTime: '13:00',
    endTime: '17:00',
    location: '잔디공터 일대',
    isSun: true,
  },
  {
    id: '3',
    tags: [
      { color: 'pk200', text: 'LIVE' },
      { color: 'ye200', text: '콘텐츠' },
    ],
    title: '호공 레이스 (DIY 배 타기)',
    startTime: '13:00',
    endTime: '15:00',
    location: '호수공원',
    isSun: true,
  },
  {
    id: '4',
    tags: [
      { color: 'pk200', text: 'LIVE' },
      { color: 'ye200', text: '콘텐츠' },
    ],
    title: '바이킹 체험',
    startTime: '13:00',
    endTime: '19:00',
    location: '제2과학기술관 옆 주차장',
    isSun: true,
  },
  {
    id: '5',
    tags: [
      { color: 'pk200', text: 'LIVE' },
      { color: 'ye200', text: '콘텐츠' },
    ],
    title: 'YOUTH : SPRING 피크닉존',
    startTime: '11:00',
    endTime: '18:00',
    location: '잔디공터',
    isSun: true,
  },
  {
    id: '6',
    tags: [
      { color: 'pk200', text: 'LIVE' },
      { color: 'ye200', text: '콘텐츠' },
    ],
    title: '한 대 맞고 더블로 가! (펀치 기계)',
    startTime: '11:00',
    endTime: '17:00',
    location: '잔디공터',
    isSun: true,
  },
  {
    id: '7',
    tags: [
      { color: 'pk200', text: 'LIVE' },
      { color: 'ye200', text: '콘텐츠' },
    ],
    title: '사탕처럼 달콤하다는데? (친구팅)',
    startTime: '11:00',
    endTime: '17:00',
    location: '호수공원 신전',
    isSun: true,
  },
  {
    id: '8',
    tags: [
      { color: 'pk200', text: 'LIVE' },
      { color: 'ye200', text: '콘텐츠' },
    ],
    title: '사탕처럼 달콤하다는데? (소개팅)',
    startTime: '11:00',
    endTime: '15:00',
    location: '호수공원 신전',
    isSun: true,
  },
  {
    id: '9',
    tags: [
      { color: 'pk200', text: 'LIVE' },
      { color: 'ye200', text: '콘텐츠' },
    ],
    title: '스탬프랠리',
    startTime: '11:00',
    endTime: '21:00',
    location: '미정',
    isSun: true,
  },
  {
    id: '10',
    tags: [
      { color: 'pk200', text: 'LIVE' },
      { color: 'ye200', text: '콘텐츠' },
    ],
    title: '드레스코드 이벤트',
    startTime: '00:00',
    endTime: '00:00',
    location: '미정',
    isSun: true,
  },
  {
    id: '11',
    tags: [
      { color: 'pk200', text: 'LIVE' },
      { color: 'ye200', text: '콘텐츠' },
    ],
    title: '청춘기록 포토존',
    startTime: '11:00',
    endTime: '17:00',
    location: '잔디공터',
    isSun: true,
  },
];
