import { LostItem, DayType } from '@/features/lost/components/ItemList.types';
import defaultImage from '@/assets/images/performance/day1-newjeans.webp';

export const lostItemsByDay: Record<DayType, LostItem[]> = {
  '1일차': [
    {
      id: 1,
      imageUrl: defaultImage,
      name: '아이패드 케이스',
      location: '운영 부스',
      isDeliveredToStaff: true,
    },
    {
      id: 2,
      imageUrl: defaultImage,
      name: '검정 우산',
      location: '중앙 무대 앞',
      isDeliveredToStaff: false,
    },
    { id: 3, imageUrl: defaultImage, name: '물병', location: '푸드존', isDeliveredToStaff: false },
    {
      id: 4,
      imageUrl: defaultImage,
      name: '화장품 파우치',
      location: '화장실 근처',
      isDeliveredToStaff: true,
    },
    {
      id: 5,
      imageUrl: defaultImage,
      name: '노란 우산',
      location: '출입구',
      isDeliveredToStaff: false,
    },
    {
      id: 6,
      imageUrl: defaultImage,
      name: '카드지갑',
      location: '편의점 옆',
      isDeliveredToStaff: true,
    },
    {
      id: 7,
      imageUrl: defaultImage,
      name: '빨간 텀블러',
      location: '무대 뒤쪽',
      isDeliveredToStaff: false,
    },
    {
      id: 8,
      imageUrl: defaultImage,
      name: '노트북 충전기',
      location: '정보부스',
      isDeliveredToStaff: true,
    },
    {
      id: 9,
      imageUrl: defaultImage,
      name: '검정 장갑',
      location: '벤치 옆',
      isDeliveredToStaff: false,
    },
  ],
  '2일차': [
    {
      id: 10,
      imageUrl: defaultImage,
      name: '모자',
      location: '공연장 입구',
      isDeliveredToStaff: true,
    },
    {
      id: 11,
      imageUrl: defaultImage,
      name: '휴대폰',
      location: '부스 B',
      isDeliveredToStaff: true,
    },
    {
      id: 12,
      imageUrl: defaultImage,
      name: '에코백',
      location: '의료지원센터',
      isDeliveredToStaff: false,
    },
    {
      id: 13,
      imageUrl: defaultImage,
      name: '보조배터리',
      location: '이벤트 존',
      isDeliveredToStaff: true,
    },
    {
      id: 14,
      imageUrl: defaultImage,
      name: '지갑',
      location: '음식 부스 뒤',
      isDeliveredToStaff: false,
    },
    {
      id: 15,
      imageUrl: defaultImage,
      name: '휴대폰 케이스',
      location: '출입구',
      isDeliveredToStaff: true,
    },
    {
      id: 16,
      imageUrl: defaultImage,
      name: '아이폰 충전기',
      location: '휴게실',
      isDeliveredToStaff: false,
    },
    {
      id: 17,
      imageUrl: defaultImage,
      name: '메모장',
      location: '캠핑존',
      isDeliveredToStaff: true,
    },
    {
      id: 18,
      imageUrl: defaultImage,
      name: '검은 슬리퍼',
      location: '잔디밭',
      isDeliveredToStaff: false,
    },
  ],
  '3일차': [
    { id: 19, imageUrl: defaultImage, name: '백팩', location: '무대 앞', isDeliveredToStaff: true },
    {
      id: 20,
      imageUrl: defaultImage,
      name: '학생증',
      location: '출구 쪽',
      isDeliveredToStaff: false,
    },
    {
      id: 21,
      imageUrl: defaultImage,
      name: '텀블러',
      location: '의료부스 근처',
      isDeliveredToStaff: true,
    },
    {
      id: 22,
      imageUrl: defaultImage,
      name: '헤드폰',
      location: '부스 D',
      isDeliveredToStaff: false,
    },
    {
      id: 23,
      imageUrl: defaultImage,
      name: '마스크팩 봉투',
      location: '화장실 근처',
      isDeliveredToStaff: false,
    },
    {
      id: 24,
      imageUrl: defaultImage,
      name: '야구 모자',
      location: '무대 뒷편',
      isDeliveredToStaff: true,
    },
    {
      id: 25,
      imageUrl: defaultImage,
      name: '노트북 파우치',
      location: '지원 센터',
      isDeliveredToStaff: false,
    },
    {
      id: 26,
      imageUrl: defaultImage,
      name: '운동화',
      location: '계단 앞',
      isDeliveredToStaff: true,
    },
    { id: 27, imageUrl: defaultImage, name: '손수건', location: '매점', isDeliveredToStaff: false },
  ],
};
