import { LostItem, DayType } from '@/features/lost/components/main/ItemList.types';
import defaultImage from '@/assets/images/performance/day1-newjeans.webp';

export const lostItemsByDay: Record<DayType, LostItem[]> = {
  '1일차': [
    {
      id: 1,
      imageUrl: defaultImage,
      name: '아이패드 케이스케이스',
      location: '운영 부스부스부스부스',
      isDeliveredToStaff: true,
      description: '검정색 가죽 재질, 펜슬 수납칸 있음',
      time: '12:00~14:00',
      day: '1일차',
    },
    {
      id: 2,
      imageUrl: defaultImage,
      name: '검정 우산',
      location: '중앙 무대 앞',
      isDeliveredToStaff: false,
      description: '자동 우산, 손잡이에 이름표 있음',
      time: '14:00~16:00',
      day: '1일차',
    },
    {
      id: 3,
      imageUrl: defaultImage,
      name: '물병',
      location: '푸드존',
      isDeliveredToStaff: false,
      description: '은색 텀블러형 물병, 브랜드 로고 있음',
      time: '12:00~14:00',
      day: '1일차',
    },
    {
      id: 4,
      imageUrl: defaultImage,
      name: '화장품 파우치',
      location: '화장실 근처',
      isDeliveredToStaff: true,
      description: '핑크색 파우치, 안에 립스틱 3개 있음',
      time: '16:00~18:00',
      day: '1일차',
    },
    {
      id: 5,
      imageUrl: defaultImage,
      name: '노란 우산',
      location: '출입구',
      isDeliveredToStaff: false,
      description: '노란색 수동 우산, 약간 젖어 있음',
      time: '10:00~12:00',
      day: '1일차',
    },
    {
      id: 6,
      imageUrl: defaultImage,
      name: '카드지갑',
      location: '편의점 옆',
      isDeliveredToStaff: true,
      description: '브라운 색상, 안에 신분증 포함',
      time: '18:00~20:00',
      day: '1일차',
    },
    {
      id: 7,
      imageUrl: defaultImage,
      name: '빨간 텀블러',
      location: '무대 뒤쪽',
      isDeliveredToStaff: false,
      description: '스타벅스 한정판, 긁힌 자국 있음',
      time: '14:00~16:00',
      day: '1일차',
    },
    {
      id: 8,
      imageUrl: defaultImage,
      name: '노트북 충전기',
      location: '정보부스',
      isDeliveredToStaff: true,
      description: '맥북 충전기, 케이블 길게 말려 있음',
      time: '12:00~14:00',
      day: '1일차',
    },
    {
      id: 9,
      imageUrl: defaultImage,
      name: '검정 장갑',
      location: '벤치 옆',
      isDeliveredToStaff: false,
      description: '겨울용 장갑, 한 쪽 손목에 구멍 있음',
      time: '10:00~12:00',
      day: '1일차',
    },
  ],

  '2일차': [
    {
      id: 10,
      imageUrl: defaultImage,
      name: '모자',
      location: '공연장 입구',
      isDeliveredToStaff: true,
      description: '검정색 볼캡, 앞에 로고 있음',
      time: '10:00~12:00',
      day: '2일차',
    },
    {
      id: 11,
      imageUrl: defaultImage,
      name: '휴대폰',
      location: '부스 B',
      isDeliveredToStaff: true,
      description: '검정색 아이폰, 뒷면에 흠집 있음',
      time: '12:00~14:00',
      day: '2일차',
    },
    {
      id: 12,
      imageUrl: defaultImage,
      name: '에코백',
      location: '의료지원센터',
      isDeliveredToStaff: false,
      description: '하얀 천 가방, 안에 노트와 펜 있음',
      time: '14:00~16:00',
      day: '2일차',
    },
    {
      id: 13,
      imageUrl: defaultImage,
      name: '보조배터리',
      location: '이벤트 존',
      isDeliveredToStaff: true,
      description: '샤오미 제품, 회색',
      time: '16:00~18:00',
      day: '2일차',
    },
    {
      id: 14,
      imageUrl: defaultImage,
      name: '지갑',
      location: '음식 부스 뒤',
      isDeliveredToStaff: false,
      description: '여성용 장지갑, 내부에 현금 있음',
      time: '18:00~20:00',
      day: '2일차',
    },
    {
      id: 15,
      imageUrl: defaultImage,
      name: '휴대폰 케이스',
      location: '출입구',
      isDeliveredToStaff: true,
      description: '고양이 그림이 있는 실리콘 케이스',
      time: '10:00~12:00',
      day: '2일차',
    },
    {
      id: 16,
      imageUrl: defaultImage,
      name: '아이폰 충전기',
      location: '휴게실',
      isDeliveredToStaff: false,
      description: '화이트 컬러, 약간 노후됨',
      time: '12:00~14:00',
      day: '2일차',
    },
    {
      id: 17,
      imageUrl: defaultImage,
      name: '메모장',
      location: '캠핑존',
      isDeliveredToStaff: true,
      description: '작은 스프링 노트, 표지에 이름 있음',
      time: '14:00~16:00',
      day: '2일차',
    },
    {
      id: 18,
      imageUrl: defaultImage,
      name: '검은 슬리퍼',
      location: '잔디밭',
      isDeliveredToStaff: false,
      description: '남성용, 사이즈 270',
      time: '16:00~18:00',
      day: '2일차',
    },
  ],

  '3일차': [
    {
      id: 19,
      imageUrl: defaultImage,
      name: '백팩',
      location: '무대 앞',
      isDeliveredToStaff: true,
      description: '회색 백팩, 앞주머니에 열쇠고리',
      time: '10:00~12:00',
      day: '3일차',
    },
    {
      id: 20,
      imageUrl: defaultImage,
      name: '학생증',
      location: '출구 쪽',
      isDeliveredToStaff: false,
      description: 'OO대학교 학생증, 카드지갑 없이 단독',
      time: '12:00~14:00',
      day: '3일차',
    },
    {
      id: 21,
      imageUrl: defaultImage,
      name: '텀블러',
      location: '의료부스 근처',
      isDeliveredToStaff: true,
      description: '검정색, 로고 없음',
      time: '14:00~16:00',
      day: '3일차',
    },
    {
      id: 22,
      imageUrl: defaultImage,
      name: '헤드폰',
      location: '부스 D',
      isDeliveredToStaff: false,
      description: '소니 무선 헤드폰, 오른쪽 귀 덮개 손상',
      time: '16:00~18:00',
      day: '3일차',
    },
    {
      id: 23,
      imageUrl: defaultImage,
      name: '마스크팩 봉투',
      location: '화장실 근처',
      isDeliveredToStaff: false,
      description: '사용 전 제품, 5개 들이',
      time: '18:00~20:00',
      day: '3일차',
    },
    {
      id: 24,
      imageUrl: defaultImage,
      name: '야구 모자',
      location: '무대 뒷편',
      isDeliveredToStaff: true,
      description: '하늘색, 브랜드 로고 있음',
      time: '12:00~14:00',
      day: '3일차',
    },
    {
      id: 25,
      imageUrl: defaultImage,
      name: '노트북 파우치',
      location: '지원 센터',
      isDeliveredToStaff: false,
      description: '노트북 파우치, 13인치용, 회색',
      time: '14:00~16:00',
      day: '3일차',
    },
    {
      id: 26,
      imageUrl: defaultImage,
      name: '운동화',
      location: '계단 앞',
      isDeliveredToStaff: true,
      description: '나이키 흰색 운동화, 좌우 밸런스 다름',
      time: '16:00~18:00',
      day: '3일차',
    },
    {
      id: 27,
      imageUrl: defaultImage,
      name: '손수건',
      location: '매점',
      isDeliveredToStaff: false,
      description: '하늘색 손수건, 무늬 있음',
      time: '10:00~12:00',
      day: '3일차',
    },
  ],
};
