import TestImage from '@/assets/images/performance/day1-newjeans.webp';

export const performanceData = {
  '1일차': [
    {
      backgroundUrl: TestImage,
      singer: '뉴진스',
      time: '21:00~22:00',
      description: 'NewJeans는 대한민국의 걸그룹이다...',
      songList: [
        { image: TestImage, name: 'OMG' },
        { image: TestImage, name: 'Hype' },
        { image: TestImage, name: 'Ditto' },
        { image: TestImage, name: 'Attention' },
        { image: TestImage, name: 'Cookie' },
      ],
    },
    {
      backgroundUrl: TestImage,
      singer: '아이브',
      time: '20:00~21:00',
      description: 'IVE는 완성형 비주얼과 중독성 있는 음악으로...',
      songList: [
        { image: TestImage, name: 'LOVE DIVE' },
        { image: TestImage, name: 'I AM' },
        { image: TestImage, name: 'ELEVEN' },
        { image: TestImage, name: 'After LIKE' },
        { image: TestImage, name: 'Kitsch' },
      ],
    },
    {
      backgroundUrl: TestImage,
      singer: '엔믹스',
      time: '19:00~20:00',
      description: 'NMIXX는 퍼포먼스 중심의 6인조 걸그룹이다.',
      songList: [
        { image: TestImage, name: 'O.O' },
        { image: TestImage, name: 'DICE' },
        { image: TestImage, name: 'Love Me Like This' },
        { image: TestImage, name: 'Young, Dumb, Stupid' },
        { image: TestImage, name: 'Funky Glitter Christmas' },
      ],
    },
    {
      backgroundUrl: TestImage,
      singer: '르세라핌',
      time: '18:00~19:00',
      description: 'LE SSERAFIM은 “IM FEARLESS”를 뜻하는...',
      songList: [
        { image: TestImage, name: 'FEARLESS' },
        { image: TestImage, name: 'ANTIFRAGILE' },
        { image: TestImage, name: 'UNFORGIVEN' },
        { image: TestImage, name: 'Perfect Night' },
        { image: TestImage, name: 'Smart' },
      ],
    },
    {
      backgroundUrl: TestImage,
      singer: '에스파',
      time: '17:00~18:00',
      description: 'aespa는 가상세계 세계관을 가진 걸그룹이다.',
      songList: [
        { image: TestImage, name: 'Next Level' },
        { image: TestImage, name: 'Savage' },
        { image: TestImage, name: 'Black Mamba' },
        { image: TestImage, name: 'Spicy' },
        { image: TestImage, name: 'Drama' },
      ],
    },
  ],
  '2일차': [
    {
      backgroundUrl: TestImage,
      singer: '세븐틴',
      time: '21:00~22:00',
      description: 'SEVENTEEN은 13인조 자체 제작 보이그룹이다.',
      songList: [
        { image: TestImage, name: 'HOT' },
        { image: TestImage, name: 'Super' },
        { image: TestImage, name: 'Clap' },
        { image: TestImage, name: 'HOME' },
        { image: TestImage, name: 'Rock with you' },
      ],
    },
    {
      backgroundUrl: TestImage,
      singer: 'TXT',
      time: '20:00~21:00',
      description: '투모로우바이투게더는 하이브 소속 5인조 보이그룹이다.',
      songList: [
        { image: TestImage, name: 'Sugar Rush Ride' },
        { image: TestImage, name: 'Good Boy Gone Bad' },
        { image: TestImage, name: '0X1=LOVESONG' },
        { image: TestImage, name: 'Blue Hour' },
        { image: TestImage, name: 'LO$ER=LO♡ER' },
      ],
    },
    {
      backgroundUrl: TestImage,
      singer: '엔하이픈',
      time: '19:00~20:00',
      description: 'ENHYPEN은 글로벌 오디션을 통해 결성된 7인조 보이그룹이다.',
      songList: [
        { image: TestImage, name: 'FEVER' },
        { image: TestImage, name: 'Bite Me' },
        { image: TestImage, name: 'Polaroid Love' },
        { image: TestImage, name: 'Future Perfect' },
        { image: TestImage, name: 'Tamed-Dashed' },
      ],
    },
    {
      backgroundUrl: TestImage,
      singer: 'NCT DREAM',
      time: '18:00~19:00',
      description: 'NCT DREAM은 7인조 보이그룹 유닛으로 활발히 활동 중이다.',
      songList: [
        { image: TestImage, name: 'Candy' },
        { image: TestImage, name: 'Beatbox' },
        { image: TestImage, name: 'Hello Future' },
        { image: TestImage, name: 'BOOM' },
        { image: TestImage, name: 'Ridin’' },
      ],
    },
    {
      backgroundUrl: TestImage,
      singer: '트와이스',
      time: '17:00~18:00',
      description: 'TWICE는 JYP 소속 9인조 걸그룹으로 다채로운 음악을 선보인다.',
      songList: [
        { image: TestImage, name: 'Cheer Up' },
        { image: TestImage, name: 'TT' },
        { image: TestImage, name: 'LIKEY' },
        { image: TestImage, name: 'Feel Special' },
        { image: TestImage, name: 'FANCY' },
      ],
    },
  ],
  '3일차': [
    {
      backgroundUrl: TestImage,
      singer: 'BTS',
      time: '21:00~22:00',
      description: '방탄소년단은 글로벌 K-POP 대표 그룹이다.',
      songList: [
        { image: TestImage, name: 'Dynamite' },
        { image: TestImage, name: 'Butter' },
        { image: TestImage, name: 'Spring Day' },
        { image: TestImage, name: 'IDOL' },
        { image: TestImage, name: 'FAKE LOVE' },
      ],
    },
    {
      backgroundUrl: TestImage,
      singer: '블랙핑크',
      time: '20:00~21:00',
      description: 'BLACKPINK는 세계적인 인기를 얻고 있는 4인조 걸그룹이다.',
      songList: [
        { image: TestImage, name: 'How You Like That' },
        { image: TestImage, name: 'DDU-DU DDU-DU' },
        { image: TestImage, name: 'Kill This Love' },
        { image: TestImage, name: 'Pink Venom' },
        { image: TestImage, name: 'As If It’s Your Last' },
      ],
    },
    {
      backgroundUrl: TestImage,
      singer: '스테이씨',
      time: '19:00~20:00',
      description: 'STAYC는 상큼한 6인조 걸그룹이다.',
      songList: [
        { image: TestImage, name: 'ASAP' },
        { image: TestImage, name: 'RUN2U' },
        { image: TestImage, name: 'Bubble' },
        { image: TestImage, name: 'Teddy Bear' },
        { image: TestImage, name: 'Stereotype' },
      ],
    },
    {
      backgroundUrl: TestImage,
      singer: 'ITZY',
      time: '18:00~19:00',
      description: 'ITZY는 당당한 콘셉트와 퍼포먼스를 지닌 5인조 걸그룹이다.',
      songList: [
        { image: TestImage, name: 'WANNABE' },
        { image: TestImage, name: 'DALLA DALLA' },
        { image: TestImage, name: 'ICY' },
        { image: TestImage, name: 'Not Shy' },
        { image: TestImage, name: 'SNEAKERS' },
      ],
    },
    {
      backgroundUrl: TestImage,
      singer: '레드벨벳',
      time: '17:00~18:00',
      description: 'Red Velvet은 다양한 콘셉트를 소화하는 다재다능한 걸그룹이다.',
      songList: [
        { image: TestImage, name: 'Red Flavor' },
        { image: TestImage, name: 'Peek-A-Boo' },
        { image: TestImage, name: 'Feel My Rhythm' },
        { image: TestImage, name: 'Psycho' },
        { image: TestImage, name: 'Bad Boy' },
      ],
    },
  ],
};
